"""updated user daily summary table

Revision ID: 0c67fe0fc1b1
Revises: 5ac1f40eda1c
Create Date: 2026-04-24 16:03:37.983147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c67fe0fc1b1'
down_revision: Union[str, Sequence[str], None] = '5ac1f40eda1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_locations_timestamp'), 'user_locations', ['timestamp'], unique=False)
    op.drop_constraint(op.f('unique_user_date'), 'user_daily_summary', type_='unique')
    op.add_column('user_place_visits', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user_place_visits', sa.Column('lon', sa.Float(), nullable=True))
    op.alter_column(
        'user_places',
        'lat',
        existing_type=sa.String(),
        type_=sa.Float(),
        postgresql_using="lat::double precision"
    )

    op.alter_column(
        'user_places',
        'lon',
        existing_type=sa.String(),
        type_=sa.Float(),
        postgresql_using="lon::double precision"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_places', 'lon',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_places', 'lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('user_place_visits', 'lon')
    op.drop_column('user_place_visits', 'lat')
    op.create_unique_constraint(op.f('unique_user_date'), 'user_daily_summary', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_locations_timestamp'), table_name='user_locations')
    op.drop_table('user_locations')
    # ### end Alembic commands ###
