"""initial schema

Revision ID: 1a11b6e4edc6
Revises: 893888226311
Create Date: 2026-04-21 12:39:41.675470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a11b6e4edc6'
down_revision: Union[str, Sequence[str], None] = '893888226311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('hobby_hours', sa.Float(), nullable=True))
    op.drop_column('routines', 'Hobby_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('Hobby_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('routines', 'hobby_hours')
    # ### end Alembic commands ###
