"""updated user daily summary table

Revision ID: 5ac1f40eda1c
Revises: eecda0b08208
Create Date: 2026-04-24 12:29:21.294000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac1f40eda1c'
down_revision: Union[str, Sequence[str], None] = 'eecda0b08208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_daily_summary', sa.Column('wake_time', sa.DateTime(), nullable=True))
    op.add_column('user_daily_summary', sa.Column('sleep_time', sa.DateTime(), nullable=True))
    op.add_column('user_daily_summary', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('user_daily_summary', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('unique_user_date'), 'user_daily_summary', type_='unique')
    op.create_index(op.f('ix_user_daily_summary_date'), 'user_daily_summary', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_summary_date'), table_name='user_daily_summary')
    op.create_unique_constraint(op.f('unique_user_date'), 'user_daily_summary', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_daily_summary', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('user_daily_summary', 'created_at')
    op.drop_column('user_daily_summary', 'sleep_time')
    op.drop_column('user_daily_summary', 'wake_time')
    # ### end Alembic commands ###
