"""updated user daily summary table

Revision ID: eecda0b08208
Revises: 418e06450568
Create Date: 2026-04-24 12:27:12.292805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eecda0b08208'
down_revision: Union[str, Sequence[str], None] = '418e06450568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_daily_summary', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_daily_summary_date'), table_name='user_daily_summary')
    op.create_unique_constraint('unique_user_date', 'user_daily_summary', ['user_id', 'date'])
    op.drop_column('user_daily_summary', 'sleep_time')
    op.drop_column('user_daily_summary', 'wake_time')
    op.drop_column('user_daily_summary', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_daily_summary', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_daily_summary', sa.Column('wake_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_daily_summary', sa.Column('sleep_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_user_date', 'user_daily_summary', type_='unique')
    op.create_index(op.f('ix_user_daily_summary_date'), 'user_daily_summary', ['date'], unique=False)
    op.alter_column('user_daily_summary', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
